### ISSUE TITLE
 [6.0.2] compatibility with Symfony 4

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compatinfo#316]
regression #310 is back

The fix is in master but not in 6.0 branch

`PHP Fatal error:  Declaration of Bartlett\CompatInfo\Application\Event\Dispatcher\EventDispatcher::dispatch(object $event, ?string $eventName = null): object must be compatible with Symfony\Component\EventDispatcher\EventDispatcher::dispatch($event) in ...`

**Comment by remicollet** [comment]
Fix for #309 is also missing...

**Comment by llaville** [comment]
Thanks for reporting, I'll fix it now

**Comment by llaville** [comment]
Two commits (fixes) was git cherry-picked from master branch to synchronize branch 6.0

**Comment by remicollet** [comment]
Also missing in 6.1 branch ?

**Comment by llaville** [comment]
no, I've just checked it

**Comment by llaville** [comment]
FYI: I plan to release the v6.1.0 in 3 days

**Comment by llaville** [comment]
@remicollet FYI (#317) ; php-compatinfo-db 3.17.0 will be released tomorrow

**Comment by llaville** [comment]
Feel free to reopen this issue, if you think I've missed something
