### ISSUE TITLE
Warning: Undefined array key "php.all" 

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compatinfo#344]
Running the analyser:

$ bin/phpcompatinfo --version
6.2.x-dev@f2684a1

Warning: Undefined array key "php.all" in /tmp/php-compatinfo/src/Application/Extension/Reporter/ConsoleReporter.php on line 230
Warning: Undefined array key "php.all" in /tmp/php-compatinfo/src/Application/Extension/Reporter/ConsoleReporter.php on line 230

(analyser run on a small project https://github.com/php-fedora/autoloader)

**Comment by llaville** [comment]
Thanks to make CompatInfo 6.2 better !
