### ISSUE TITLE
regression: DATABASE_URL from env doesn't work in new 6.5.x

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compatinfo#356]
Was working as expected in 6.4.x

```
$ phpcompatinfo diagnose
    ...
    >  [env(APP_DATABASE_URL)] sqlite:////usr/share/php-bartlett-PHP-CompatInfo/data/compatinfo-db.sqlite
    ....
```
First call is OK

```
$ export DATABASE_URL=sqlite:////tmp/compatinfo-db.sqlite
$ phpcompatinfo diagnose
    ...
    >  [env(APP_DATABASE_URL)] sqlite:////usr/share/php-bartlett-PHP-CompatInfo/data/compatinfo-db.sqlite
    ....
```
Second call is broken, DATABASE_URL env is ignored

Workaround 
```
$ rm -rf ~/.cache/bartlett/
$ phpcompatinfo diagnose
    ...
    >  [env(APP_DATABASE_URL)] sqlite:////tmp/compatinfo-db.sqlite
    ....
```

So... cache issue.

So, this is a regression (tested with 6.5.1)

**Comment by llaville** [comment]
> So... cache issue.
> 
> So, this is a regression (tested with 6.5.1)

I confirm it's a Symfony Container Compiled cache issue on my side. Good catch @remicollet !
I'll fix it tomorrow morning, because I've not enough time tonight.

**Comment by llaville** [comment]
As it's related to database, the fix will be applied on PHP_CompatInfoDB.

FYI: as I've also some minor changes to do on CompatInfo, I'll also release a bugfix 6.5.2

**Comment by llaville** [comment]
@remicollet FYI : 
- Code of CompatInfoDB 4.6.1 is ready on branch https://github.com/llaville/php-compatinfo-db/tree/4.6
- CompatInfo 6.5.1 may be used with it for testing (composer constraint is `"bartlett/php-compatinfo-db": "4.6.x-dev"`)

I'll release both **CompatInfoDB 4.6.1** and **CompatInfo 6.5.2** in few hours unless we found another critical issue (but I don't think so ;-)

**Comment by llaville** [comment]
Versions **CompatInfoDB 4.6.1** and **CompatInfo 6.5.2** are now available.
