### ISSUE TITLE
PHP 8.3 compatibility and CompatInfo 7.0

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compatinfo#364]
Only about being able to run it

`PHP Fatal error:  Uncaught Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file "up-to-php83.php" does not exist ...`

**Comment by llaville** [comment]
Hello @remicollet 
You should probably tried with wrong branch. File exists in branch `8.0` => see list at https://github.com/llaville/php-compatinfo/tree/8.0/config/set

I've tested is few minutes ago again with PHP 8.3.0RC5.
As Docker Image of 8.3.0RC6 is not yet available, I've not check it with !
 with
If you're still in trouble, please specify your platform info with `diagnose` command. As files `up-to-phpXX.php` are only used in context of `analyser:run` command.

**Comment by remicollet** [comment]
> You should probably tried with wrong branch. 

I'm using released version 7.0.0

**Comment by llaville** [comment]
> > You should probably tried with wrong branch.
> 
> I'm using released version 7.0.0

As PHP 8.3.0 stable version is not yet available, I consider that PHP CompatInfo 7.0.0 is not able to run with this platform.
I'm working on a new major version  CompatInfo 8.0.0 (branch 8.0) that will support it ! If you want to give a try, you're welcome 

Reason of this major version is multiple: 
- drop support of PHP 8.0.0 that will reach EOL when 8.3.0 stable will be officially release
- synchronize with CompatInfoDB 6.0.0 that will also drop support of PHP 8.0
- add new features (not yet documented/specified)

**Comment by llaville** [comment]
I keep your feedback in mind and will release a 7.0.1 that will limit PHP version to 8.2 by composer constraint.
It will occurs when PHP 8.3.0 stable will be available and CompatInfo 8.0.0 will be ready too !

**Comment by remicollet** [comment]
> I keep your feedback in mind and will release a 7.0.1 that will limit PHP version to 8.2 by composer constraint.

So I will have to remove the Fedora package as Fedora has 8.3 for a while.

> As PHP 8.3.0 stable version is not yet available,

Since RC1, ABI/API is "finale", no more change expected

> drop support of PHP 8.0.0 that will reach EOL when 8.3.0 stable will be officially release

8.0 may have 1 more support year

=> https://wiki.php.net/rfc/release_cycle_update

**Comment by llaville** [comment]
> 8.0 may have 1 more support year
> 
> => https://wiki.php.net/rfc/release_cycle_update

You learn me, but this RFC is not yet accepted and others package maintainers don't know it i suppose. 
There is a hurry now : https://www.php.net/supported-versions

**Comment by remicollet** [comment]
> There is a hurry now

Why ?
I really think this doesn't make any sense.

There is more urgency to have developer tools ready for 8.3
as all good dev should be working on PHP 8.3 to finalize their app/library before 8.3
and this project is not ready. This is a real issue

**Comment by llaville** [comment]
No you misunderstood me. I said there is a hurry if the community want to give PHP 8.0 1 more year of support while supported versions link told us that it will reach EOL in 12 days

**Comment by remicollet** [comment]
Closing this,
I don't want to fight
I don't understand how this project work
I don't want to hurt my brain anymore
Will try to find an alternative

Notice: version 7.0.0 works nicely with 8.3.0RC6, when the missing file is there

**Comment by llaville** [comment]
I agree CompatInfo 7.0 is not ready for PHP 8.3, and I will realease a 7.0.1 to fix that just after CompatInfoDB 5.13.0 (that will fix same kind of issue)

**Comment by llaville** [comment]
@remicollet FYI CompatInfoDB 5.13 was just be released and CompatInfo 7.0.1 will be available tomorrow morning

**Comment by llaville** [comment]
Good new : Upcoming CompatInfo 7.1.0 will keep PHP 8.0 compatibility, and support of PHP 8.3 will be added
