### ISSUE TITLE
[ERROR] Lazy ghost objects cannot be enabled...

### ISSUE THREAD

**Issue by remicollet** [llaville/php-compatinfo#365]
Running with PHP 8.2 (but trying to make a 8.0 compatible archive)

```
$ composer config platform.php 8.0.99

$ composer install --no-interaction --no-progress --no-dev --optimize-autoloader

$ bin/phpcompatinfo --version
                                                                                                                        
 [ERROR] Lazy ghost objects cannot be enabled because the "symfony/var-exporter" library version 6.2 or higher is not   
         installed. Please run "composer require symfony/var-exporter:^6.2".                                            
                                                                                                                        
```

Switching to PHP 8.1 (so from Symfony 6.0 to 6.4) is a workaround

**Comment by llaville** [comment]
If you run phpcompatinfo 7.0.2 on a PHP 8.0 platform, CompatInfoDB 5.14.1 will be installed and lazy ghost objects Doctrine feature will be disabled. 
See https://github.com/llaville/php-compatinfo-db/commit/2718e7e7dc2d571ebbd9ccc6bff6a7d19dadea2d

**Comment by remicollet** [comment]
>If you run phpcompatinfo 7.0.2 on a PHP 8.0 platform, CompatInfoDB 5.14.1 will be installed and lazy ghost objects Doctrine feature will be disabled.

But if you  install PHP 8.0+ compatible version (`composer config platform.php 8.0.99`) so with CompatInfoDB 5.14.1  and Symfony 6.0, when running it with 8.2, it will try to enable lazy ghost, which requires Symfony 6.2

**Comment by remicollet** [comment]
And FYI, also sometime got

```
$ bin/phpcompatinfo --version

                                                                                                                        
 [ERROR] Too few arguments to function                                                                                  
         Bartlett_CompatInfo_Application_Kernel_ConsoleKernelProdContainer::getApplicationInterface2Service(), 0 passed 
         in /tmp/php-compatinfo/vendor/symfony/dependency-injection/Container.php on line 217 and exactly 1 expected    

```

**Comment by llaville** [comment]
I've just keep a chance to CompatInfo 7.0 users to use the recent database contents (v6..0), but I'm not in favour to keep compatibility with old components no more supported : 
- PHP 8.0 support dropped 
- Symfony new LTS is 6.4

**Comment by llaville** [comment]
Release 7.1.0 is on way !
